name: Build README

on:
  schedule:
    - cron: '0 0 * * *' # “At 00:00 everyday”
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update README
      run: |-
        python scripts/create_readme.py
        cat README.md

    - name: load to github
      run: |
        git config user.name "Automated Publisher"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m ":robot: Automated update README: ${timestamp}" || exit 0
        git push