name: Build README

on:
  schedule:
    - cron: '0 0 * * *' # “At 00:00 everyday”
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version}}    

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update README
      run: |-
        python scripts/create_readme.py
        cat README.md

    - name: load to github
      run: |
        git config user.name "Automated Publisher"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m ":robot: Automated update README: ${timestamp}" || exit 0
        git push